import Head from 'next/head';

import Nav from '@components/nav/nav';
import Section from '@components/section/section';


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function Home() {
  return (
    <>
      <Nav arr={[ 'title', 'Explore', 'Account' ]} />
      <main className="flex justify-center items-center h-full w-full pt-5 ">  
            
        <Section>
          <div></div>
          <div ></div>
          <div />  
        </Section>

      </main>
    </>
  )
}
 